apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapshot-controller
  namespace: kube-system
  labels:
    {{- include "snapshot-controller.labels" . | nindent 4 }}
spec:
  minReadySeconds: 15
  replicas: {{ .Values.replicas | default 2}}
  selector:
    matchLabels:
      app: snapshot-controller
      {{- include "snapshot-controller.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: snapshot-controller
        {{- include "snapshot-controller.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - --v=5
        - --leader-election=true
        {{- if .Values.extraArgs }}
        {{- range .Values.extraArgs }}
        - {{ . | quote }}
        {{- end }}
        {{- end }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
      serviceAccountName: snapshot-controller
