{{- if .Values.volumeSnapshotClass.create }}
apiVersion: v1
kind: Pod
metadata:
  name: "sleephook"
  namespace: kube-system
  annotations:
    helm.sh/hook-delete-policy: before-hook-creation,hook-failed,hook-succeeded
    helm.sh/hook: post-install,post-upgrade
    "helm.sh/hook-weight": "2"
  labels:
    app: sleephook
spec:
  restartPolicy: OnFailure
  containers:
  - name: sleephook
    image: gcr.io/spectro-images-public/release/spectro-kubectl:1.26.3
    args:
    - sleep
    - "{{- .Values.hooksleepTime }}"
{{- end }}