apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gslbconfigs.amko.vmware.com
spec:
  conversion:
    strategy: None
  group: amko.vmware.com
  names:
    kind: GSLBConfig
    listKind: GSLBConfigList
    plural: gslbconfigs
    shortNames:
    - gc
    singular: gslbconfig
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              gslbLeader:
                type: object
                properties:
                  controllerIP:
                    type: string
                  controllerVersion:
                    type: string
                  credentials:
                    type: string
                  tenant:
                    type: string
              logLevel:
                enum:
                - DEBUG
                - INFO
                - WARN
                - ERROR
                type: string
              memberClusters:
                items:
                  type: object
                  properties:
                    clusterContext:
                      type: string
                type: array
              refreshInterval:
                type: integer
              useCustomGlobalFqdn:
                type: boolean
          status:
            type: "object"
            properties:
              state:
                type: "string"
        required:
        - spec
    served: true
    storage: true
