installCRDs: true

operator:
  replicaCount: 1
  image:
    repository: quay.io/piraeusdatastore/piraeus-operator
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
  options: []
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi
  priorityClassName: ""
  nodeSelector: { }
  tolerations:
    - key: drbd.linbit.com/lost-quorum
      effect: NoSchedule
    - key: drbd.linbit.com/force-io-error
      effect: NoSchedule
  affinity: { }

webhook:
  timeoutSeconds: 2
  failurePolicy: Fail

tls:
  certificateSecret: ""
  autogenerate: true
  renew: false
  certManagerIssuerRef: {}

imageConfigOverride: []
  # - base: example.com/piraeus
  #   components:
  #     linstor-csi:
  #       image: linstor-csi
  #       tag: my-custom-tag
  #   Results in the image example.com/piraeus/linstor-csi:my-custom-tag being used.
  #   See templates/config.yaml for available components.
