pack:
  content:
    charts:
      - repo: https://charts.k8sgpt.ai
        name: k8sgpt/k8sgpt-operator
        version: 0.0.20
    images:
      - image: ghcr.io/k8sgpt-ai/k8sgpt-operator:v0.0.20
      - image: gcr.io/kubebuilder/kube-rbac-proxy:v0.14.1

  namespace: k8sgpt-operator-system

charts:
  k8sgpt-operator:
    serviceMonitor:
      enabled: false
      additionalLabels: {}
    grafanaDashboard:
      enabled: false
      folder:
        annotaion: grafana_folder
        name: ai
      label:
        key: grafana_dashboard
        value: "1"
    controllerManager:
      kubeRbacProxy:
        containerSecurityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        image:
          repository: gcr.io/kubebuilder/kube-rbac-proxy
          tag: v0.14.1
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 64Mi
      manager:
        containerSecurityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        image:
          repository: ghcr.io/k8sgpt-ai/k8sgpt-operator
          tag: v0.0.20
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      replicas: 1
    kubernetesClusterDomain: cluster.local
    metricsService:
      ports:
      - name: https
        port: 8443
        protocol: TCP
        targetPort: https
      type: ClusterIP

manifests:
  k8sgpt:
    backend: localai
    baseUrl: http://local-ai.local-ai.svc.cluster.local:8080/v1
    noCache: false
    model: "ggml-gpt4all-j.bin"
    version: v0.3.8
    enableAI: true
    openAiApiKey: ""
