apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtual-machine-orchestrator-admin
  labels:
    {{- include "virtual-machine-orchestrator.labels" . | nindent 4 }}
rules:
- apiGroups: ["spectrocloud.com"] # "" indicates the core API group
  resources: ["vmtemplates"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: ["kubevirt.io", "subresources.kubevirt.io", "cdi.kubevirt.io", "snapshot.kubevirt.io", "migrations.kubevirt.io"]
  resources: ["*"]
  verbs: ["create", "delete", "list", "get", "update","patch"]
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["*"]
  verbs: ["create", "delete", "list", "get", "update","patch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims","pods", "events", "namespaces", "services"]
  verbs: ["*"]