{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: virtual-machine-orchestrator
  labels:
    {{- include "virtual-machine-orchestrator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "virtual-machine-orchestrator.serviceAccountName" . }}
  apiGroup: ""
  namespace: {{ include "virtual-machine-orchestrator.namespace" . }}
roleRef:
  kind: ClusterRole
  name: virtual-machine-orchestrator-admin
  apiGroup: rbac.authorization.k8s.io
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: virtual-machine-orchestrator
  labels:
    {{- include "virtual-machine-orchestrator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ""
  namespace: {{ include "virtual-machine-orchestrator.namespace" . }}
roleRef:
  kind: ClusterRole
  name: virtual-machine-orchestrator-admin
  apiGroup: rbac.authorization.k8s.io
{{- end }}