apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "virtual-machine-orchestrator.fullname" . }}
  labels:
    {{- include "virtual-machine-orchestrator.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "virtual-machine-orchestrator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "virtual-machine-orchestrator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "virtual-machine-orchestrator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "virtual-machine-orchestrator.fullname" . }}
          volumeMounts:
            - name: vm-dashboard-config
              mountPath: /config
            - name: tls
              mountPath: "/cert/"
              readOnly: true
          args:
            - --public-dir=/opt/bridge/static
            - --config=/config/vm-dashboard-config.yaml
            - --tls-cert-file=/cert/certificate.pem
            - --tls-key-file=/cert/certificate.key
            - --ca-file=/cert/ca.pem
            - --listen=https://0.0.0.0:9000
          command:
            - /opt/bridge/bin/bridge
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: https
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /health
              port: https
              scheme: HTTPS
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - configMap:
            name: config
          name: vm-dashboard-config
        - name: tls
          secret:
            secretName: tls-certs
            optional: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
