apiVersion: v1
kind: Service
metadata:
  name: vm-dashboard
  labels:
    {{- include "virtual-machine-orchestrator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "virtual-machine-orchestrator.selectorLabels" . | nindent 4 }}
