{{- if and .Values.podSecurityPolicy.create .Values.lvmd.managed }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "topolvm.fullname" . }}-lvmd:psp:{{ template "topolvm.fullname" . }}-lvmd
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "topolvm.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "topolvm.fullname" . }}-lvmd
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:{{ template "topolvm.fullname" . }}-lvmd
---
{{- end }}
