{{- if .Values.lvmd.managed }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "topolvm.fullname" . }}-lvmd
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "topolvm.labels" . | nindent 4 }}
---
{{- end }}
