---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ovnkube-dpucniprovisioner
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  name: ovnkube-dpucniprovisioner-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: ovnkube-dpucniprovisioner
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovnkube-dpucniprovisioner
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ovnkube-dpucniprovisioner
subjects:
- kind: ServiceAccount
  name: ovnkube-dpucniprovisioner
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: ovnkube-dpucniprovisioner
  apiGroup: rbac.authorization.k8s.io
