apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multus
    tier: node
    {{- include "multus.labels" . | nindent 4 }}
  name: multus-daemon-config
  namespace: kube-system
data:
  daemon-config.json: |
    {
        "chrootDir": "/hostroot",
        "confDir": "/host/etc/cni/net.d",
        "logLevel": "verbose",
        "socketDir": "/host/run/multus/",
        "cniVersion": "0.3.1",
        "cniConfigDir": "/host/etc/cni/net.d",
        "multusConfigFile": "auto",
        "multusAutoconfigDir": "/host/etc/cni/net.d"
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dynamic-networks-controller-config
  namespace: kube-system
  labels:
    tier: node
    app: multus-dynamic-networks-controller
    {{- include "multus.labels" . | nindent 4 }}
data:
  dynamic-networks-config.json: |
    {
        "criSocketPath": "/host/run/containerd/containerd.sock",
        "multusSocketPath": "/host/run/multus/multus.sock"
    }
