apiVersion: v1
kind: ServiceAccount
metadata:
  name: multus
  namespace: kube-system
  labels:
    {{- include "multus.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynamic-networks-controller
  namespace: kube-system
  labels:
    {{- include "multus.labels" . | nindent 4 }}
