manifests:
  calico:

    # IPAM type to use. Supported types are calico-ipam, host-local
    ipamType: "calico-ipam"

    # Should be one of CALICO_IPV4POOL_IPIP or CALICO_IPV4POOL_VXLAN  
    encapsulationType: "CALICO_IPV4POOL_IPIP"

    # Should be one of Always, CrossSubnet, Never
    encapsulationMode: "Always"