annotations:
  commit: c7bd3d764a5875b42754a7ab0102654f0d246da1
  created: "2025-08-05T16:26:21+00:00"
  dpfVersion: v25.7.0-rc.2
apiVersion: v2
appVersion: 1.0.0
dependencies:
- condition: ovn-kubernetes-resource-injector.enabled
  name: ovn-kubernetes-resource-injector
  repository: ""
  version: 1.0.0
description: Helm chart to deploy ovn-kubernetes in the NVIDIA DOCA Platform Framework
  (DPF) context
home: https://ovn-kubernetes.io/
icon: https://www.ovn.org/images/ovn-logo.png
name: ovn-kubernetes-chart
sources:
- https://github.com/ovn-org/ovn-kubernetes
- https://github.com/ovn-org/ovn
type: application
version: v25.7.0-rc.2
