apiVersion: v1
kind: Service
metadata:
  name: {{ template "topolvm.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "topolvm.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: controller
    {{ include "topolvm.selectorLabels" . | nindent 4 }}
  ports:
    - name: webhook
      port: 443
      protocol: TCP
      targetPort: webhook
