{{- if and .Values.server.enabled .Values.server.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "parca.serviceAccountName" . }}
  labels:
    app: {{ include "parca.serviceAccountName" . }}
{{- include "parca.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
{{- end }}
