{{- if and (not .Values.storageCluster.spec.kvdb.internal) .Values.externalKvdb.useCertsForSSL }}
apiVersion: v1
kind: Secret
metadata:
  name: px-kvdb-auth
  namespace: kube-system
type: Opaque
data:
  kvdb-ca.crt: {{ .Values.externalKvdb.cacert | b64enc | quote }}
  kvdb.key: {{ .Values.externalKvdb.key | b64enc | quote }}
  kvdb.crt: {{ .Values.externalKvdb.cert | b64enc | quote }}
{{- end }}
---
{{- if eq .Values.license.type "essentials" }}
apiVersion: v1
kind: Secret
metadata:
  name: px-essential
  namespace: kube-system
data:
  px-essen-user-id: {{ .Values.license.essentials.userId | b64enc }}
  px-osb-endpoint: {{ .Values.license.essentials.endpoint | b64enc }}
{{- end }}
---
{{- if eq .Values.license.type "saas" }}
apiVersion: v1
data:
  account-key: {{ .Values.license.saas.key }}
kind: Secret
metadata:
  name: px-saas-key
  namespace: kube-system
{{- end }}