apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/resource-policy": "keep"
  name: linstorcluster
  namespace: {{ .Release.Namespace }}
spec:
{{ .Values.cluster.spec | toYaml | indent 2 }}