apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-sriov-device-plugin
  namespace: kube-system
  labels:
    tier: node
    app: sriovdp
spec:
  selector:
    matchLabels:
      name: sriov-device-plugin
  template:
    metadata:
      labels:
        name: sriov-device-plugin
        tier: node
        app: sriovdp
    spec:
      hostNetwork: true
      serviceAccountName: sriov-device-plugin
{{- if .Values.networkDevicePlugin.daemonset.tolerations }}
      tolerations: {{ .Values.networkDevicePlugin.daemonset.tolerations | toYaml | nindent 6 }}
{{- end }}
      containers:
      - name: kube-sriovdp
        image: "{{ .Values.networkDevicePlugin.daemonset.image }}:{{ .Values.networkDevicePlugin.daemonset.tag }}"
        imagePullPolicy: {{ .Values.networkDevicePlugin.daemonset.imagePullPolicy }}
        args:
        - --log-dir=sriovdp
        - --log-level=10
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "250m"
            memory: "40Mi"
          limits:
            cpu: 1
            memory: "200Mi"
        volumeMounts:
        - name: devicesock
          mountPath: /var/lib/kubelet/device-plugins
          readOnly: false
        - name: plugins-registry
          mountPath: /var/lib/kubelet/plugins_registry
          readOnly: false
        - name: log
          mountPath: /var/log
        - name: config-volume
          mountPath: /etc/pcidp
        - name: device-info
          mountPath: /var/run/k8s.cni.cncf.io/devinfo/dp
      volumes:
      - name: devicesock
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: plugins-registry
        hostPath:
          path: /var/lib/kubelet/plugins_registry
      - name: log
        hostPath:
          path: /var/log
      - name: device-info
        hostPath:
          path: /var/run/k8s.cni.cncf.io/devinfo/dp
          type: DirectoryOrCreate
      - name: config-volume
        configMap:
          name: sriovdp-config
          items:
          - key: config.json
            path: config.json
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-sriov-cni-ds
  namespace: kube-system
  labels:
    tier: node
    app: sriov-cni
spec:
  selector:
    matchLabels:
      name: sriov-cni
  template:
    metadata:
      labels:
        name: sriov-cni
        tier: node
        app: sriov-cni
    spec:
{{- if .Values.sriovCNI.daemonset.tolerations }}
      tolerations: {{ .Values.sriovCNI.daemonset.tolerations | toYaml | nindent 6 }}
{{- end }}
      containers:
      - name: kube-sriov-cni
        image: "{{ .Values.sriovCNI.daemonset.image }}:{{ .Values.sriovCNI.daemonset.tag }}"
        imagePullPolicy: {{ .Values.sriovCNI.daemonset.imagePullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        volumeMounts:
        - name: cnibin
          mountPath: /host/opt/cni/bin
      volumes:
      - name: cnibin
        hostPath:
          path: /opt/cni/bin