# spectrocloud.com/enabled-presets: License Models:px-essentials
pack:
  content:
    images:
      # From https://install.portworx.com/3.1.5/air-gapped
      - image: docker.io/nginxinc/nginx-unprivileged:1.25
      - image: docker.io/portworx/autopilot:1.3.15
      - image: docker.io/portworx/oci-monitor:3.1.5
      - image: docker.io/portworx/portworx-dynamic-plugin:1.1.1
      - image: docker.io/portworx/px-enterprise:3.1.5
      - image: docker.io/portworx/px-essentials:3.1.5
      - image: docker.io/portworx/px-operator:24.1.1
      - image: docker.io/openstorage/cmdexecutor:24.3.0
      - image: docker.io/openstorage/csi-attacher:v1.2.1-1
      - image: docker.io/openstorage/stork:24.3.0
      - image: docker.io/purestorage/ccm-go:1.2.2
      - image: docker.io/purestorage/log-upload:px-1.1.8
      - image: docker.io/purestorage/realtime-metrics:1.0.29
      - image: docker.io/purestorage/telemetry-envoy:1.1.16
      - image: registry.k8s.io/kube-controller-manager-amd64:v1.23.12
      - image: registry.k8s.io/kube-scheduler-amd64:v1.21.4
      - image: registry.k8s.io/kube-scheduler-amd64:v1.23.12
      - image: registry.k8s.io/pause:3.1
      - image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.9.0
      - image: registry.k8s.io/sig-storage/csi-provisioner:v3.6.1
      - image: registry.k8s.io/sig-storage/csi-resizer:v1.9.1
      - image: registry.k8s.io/sig-storage/csi-snapshotter:v8.0.1
      - image: registry.k8s.io/sig-storage/snapshot-controller:v6.3.1
      - image: quay.io/prometheus/alertmanager:v0.26.0
      - image: quay.io/prometheus/prometheus:v2.48.1
      - image: quay.io/prometheus-operator/prometheus-operator:v0.70.0
      - image: quay.io/prometheus-operator/prometheus-config-reloader:v0.70.0

# Upgrade procedure from v2.x of the pack:
# * Ensure you select a different namespace than kube-system for the operator
# * Ensure you select the kube-system namespace for the storagecluster
# * Before upgrading, scale down the portworx-operator in the kube-system namespace to 0
# * After applying the upgrade, delete the portworx-operator clusterRole and clusterRoleBinding from the cluster.
# * If you’re on K8S 1.24 or lower, also delete the px-operator PodSecurityPolicy.
# * Once the new operator is running in the new namespace, delete the portworx-operator deployment and
#   service account from the kube-system namespace.

charts:
  px-operator:
    namespace: portworx-operator

  portworx-generic:
    license:
      # Valid options for "type" are: essentials, saas, enterprise
      # If you want to deploy the PX Enterprise Trial version, or need manual offline activation,
      # select the "enterprise" type and set "activateLicense" to false.
      type: essentials
      # The next block only gets used if the type is set to "essentials"
      essentials:
        # Base64-decoded value of the px-essen-user-id value in the px-essential secret
        # Find your Essential Entitlement ID at https://central.portworx.com/profile
        userId: 1234abcd-12ab-12ab-12ab-123456abcdef
        # Base64-decoded value of the px-osb-endpoint value in the px-essential secret
        # Leave at the default value unless there are special circumstances
        endpoint: https://pxessentials.portworx.com/osb/billing/v1/register
      # The next block only gets used if the type is set to "saas"
      saas:
        key: <PAY-AS-YOU-GO-KEY>
      # The next block only gets used if the type is set to "enterprise"
      enterprise:
        activateLicense: true
        activationId: <Activation ID>
        # customLicenseServer:
        #   url: http://hostname:7070/fne/bin/capability
        #   importUnknownCa: true
        #   licenseBorrowInterval: 1w15m
        #   addFeatures:
        #   - feature1
        #   - feature2

    storageCluster:
      # When autoGenerateName is true, a name of type "px-cluster-1234abcd-12ab-12ab-12ab-123456abcdef" is generated and the "name" field is ignored
      autoGenerateName: false
      name: "px-{{.spectro.system.cluster.name}}"
      namespace: portworx
      # annotations:
      #   If you need additional annotations, specify them here
      spec: {}
        # Select a preset from the pane on the right, or use the Portworx Spec Builder to define a custom configuration and
        # then paste that spec section here. (Spec Builder: https://central.portworx.com/specGen/wizard)
        # ### Example spec
        # image: portworx/oci-monitor:3.2.0
        # imagePullPolicy: Always
        # deleteStrategy:
        #   type: UninstallAndWipe
        # kvdb:
        #   internal: true
        #   # endpoints:
        #   # - etcd:https://etcd.company.domain:2379
        #   # authSecret: px-kvdb-auth
        # storage:
        #   useAll: true
        #   journalDevice: auto
        #   kvdbDevice: /dev/sdb
        # network:
        #   dataInterface: eth0
        #   mgmtInterface: eth1
        # secretsProvider: k8s
        # stork:
        #   enabled: true
        #   args:
        #     webhook-controller: "true"
        # autopilot:
        #   enabled: true
        #   providers:
        #   - name: default
        #     params:
        #       url: http://prometheus-operator-prometheus.monitoring.svc.cluster.local:9090
        #     type: prometheus
        # runtimeOptions:
        #   default-io-profile: "6"
        # csi:
        #   enabled: true
        # monitoring:
        #   telemetry:
        #       enabled: true
        #   prometheus:
        #     enabled: false
        #     exportMetrics: true

    # To automatically create the px-vsphere-secret for VMware, uncomment this section
    # vsphereSecret:
    #   user: ""
    #   password: ""

    # To automatically create the px-azure secret for Azure, uncomment this section
    # azureSecret:
    #   tenantId:
    #   clientId:
    #   clientSecret: 

    storageClass:
      name: spectro-storage-class
      isDefaultStorageClass: true
      annotations: {}
      #   If you need additional annotations, specify them here
      reclaimPolicy: Delete # Delete or Retain
      volumeBindingMode: WaitForFirstConsumer # WaitForFirstConsumer or Immediate
      allowVolumeExpansion: true
      parameters:
        repl: "2"
        io_profile: "auto_journal"
        # nodiscard: "true"
        # priority_io: "high"
        # sharedv4: true
        # sharedv4_svc_type: "ClusterIP"
        # sharedv4_mount_options: vers=3.0,nolock
        # stork.libopenstorage.org/preferRemoteNode: "false"
        # Add additional parameters as needed (https://docs.portworx.com/portworx-install-with-kubernetes/storage-operations/create-pvcs/dynamic-provisioning/)

    # External kvdb related config, only used if storageCluster.spec.kvdb.internal = false
    externalKvdb:
      useCertsForSSL: false
      # cacert: |
      #   -----BEGIN CERTIFICATE-----
      #   < KEY DATA >
      #   -----END CERTIFICATE-----
      # key: |
      #   -----BEGIN RSA PRIVATE KEY-----
      #   < KEY DATA >
      #   -----END RSA PRIVATE KEY-----
      # cert: |
      #   -----BEGIN CERTIFICATE-----
      #   < KEY DATA >
      #   -----END CERTIFICATE-----
