{{- if and (.Capabilities.APIVersions.Has "cluster.x-k8s.io/v1beta1/MachineDrainRule") (.Values.machineDrainRule.create) }}
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDrainRule
metadata:
  name: portworx
  namespace: {{ .Values.machineDrainRule.namespace }}
spec:
  drain:
    behavior: Drain
    order: 100
  machines:
  - selector: {}
  pods:
  - selector:
      matchLabels:
        operator.libopenstorage.org/managed-by: portworx
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: {{ .Values.storageCluster.namespace }}
{{- end }}