apiVersion: v2
appVersion: 0.1.0
dependencies:
- condition: argo-cd.enabled
  name: argo-cd
  repository: https://argoproj.github.io/argo-helm
  version: 7.6.8
- condition: node-feature-discovery.enabled
  name: node-feature-discovery
  repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
  version: 0.16.5
- condition: kube-state-metrics.enabled
  name: kube-state-metrics
  repository: https://prometheus-community.github.io/helm-charts
  version: 5.25.1
- condition: grafana.enabled
  name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 8.4.6
- condition: prometheus.enabled
  name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 25.26.0
- condition: kamaji-etcd.enabled
  name: kamaji-etcd
  repository: https://clastix.github.io/charts
  version: 0.9.0
- condition: kamaji.enabled
  name: kamaji
  repository: https://clastix.github.io/charts
  version: 1.0.0
- condition: maintenance-operator-chart.enabled
  name: maintenance-operator-chart
  repository: oci://ghcr.io/mellanox
  version: 0.1.1
description: DPF Operator manages the lifecycle of a DOCA Platform Framework system.
name: dpf-operator
type: application
version: v25.1.0
