apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.csm.config.secret.name }}
  namespace: {{ .Values.csm.namespace }}
{{- if .Values.csm.config.secret.encoded }}
data:
{{- else }}
stringData:
{{- end }}
{{- if or (eq .Values.csm.type "powerflex") (eq .Values.csm.type "powerstore") }}
  config: {{ .Values.csm.config.secret.value | nindent 4 }}
{{- else if eq .Values.csm.type "powermax" }}
{{ .Values.csm.config.secret.value | toYaml | indent 2 }}
{{- end }}