pack:
  content:
    charts:
      - repo: https://go-skynet.github.io
        name: helm-charts/local-ai
        version: 2.1.1
    images:
      - image: busybox:latest
      - image: quay.io/go-skynet/local-ai:v1.23.0

  namespace: local-ai

charts:
  local-ai:
    
    deployment:
      image: quay.io/go-skynet/local-ai:v1.23.0
      env:
        rebuild: "false"
        threads: 4
        context_size: 512
      modelsPath: "/models"
    
    resources: {}

    promptTemplates: {}

    models:
      forceDownload: false

      list:
      - url: "https://gpt4all.io/models/ggml-gpt4all-j.bin"

      persistence:
        pvc:
          enabled: true
          size: 6Gi
          accessModes:
            - ReadWriteOnce

          annotations: {}

          storageClass: ~

        hostPath:
          enabled: false
          path: "/models"

    service:
      type: ClusterIP
      port: 8080
      annotations: {}
      # If using an AWS load balancer, you'll need to override the default 60s load balancer idle timeout

    ingress:
      enabled: false
      className: ""
      annotations:
        {}
      hosts:
        - host: chart-example.local
          paths:
            - path: /
              pathType: ImplementationSpecific
    
      tls: []
  
    nodeSelector: {}

    tolerations: []

    affinity: {}
