apiVersion: v2
appVersion: v0.20.0
description: Open Source Infrastructure-wide continuous profiling
home: https://parca.dev/
icon: https://avatars.githubusercontent.com/u/86306284?s=200&v=4
name: parca
sources:
- https://github.com/parca-dev/helm-charts
type: application
version: 4.19.0
