apiVersion: batch/v1
kind: Job
metadata:
  name: delete-cdi-cr
  namespace: {{ .Values.namespace | default "cdi" }}
  annotations:
    "helm.sh/hook": pre-delete
spec:
  template:
    spec:
      containers:
        - name: delete-cdi-cr
          image: gcr.io/spectro-images-public/release/spectro-kubectl:1.26.3
          command: ["/bin/sh", "-c", "kubectl get cdi -l spectrocloud.com/installed-by=spectrocloud -o jsonpath='{.items[0].metadata.name}' | xargs kubectl delete cdi"]
      serviceAccount: cdi-sa
      restartPolicy: Never