apiVersion: batch/v1
kind: Job
metadata:
  name: delete-kubevirt-cr
  namespace: {{ .Values.namespace | default "kubevirt" }}
  annotations:
    "helm.sh/hook": pre-delete
spec:
  template:
    spec:
      containers:
        - name: delete-kubevirt-cr
          image: gcr.io/spectro-images-public/release/spectro-kubectl:1.26.3
          command: ["/bin/sh", "-c", "kubectl get kv -l spectrocloud.com/installed-by=spectrocloud -o jsonpath='{.items[0].metadata.name}' | xargs kubectl delete kv"]
      serviceAccount: kubevirt-operator
      restartPolicy: Never
