{{ if not .Values.ingress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: virt-exportproxy-lb
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  selector:
    kubevirt.io: virt-exportproxy
  type: {{ .Values.service.type }}
{{ end }}
