pack:
  content:
    images: []

charts:
  vmo-quota-mgmt:
    quotas: []
      # - namespace: default
      #   limits:
      #     cpu: 9
      #   requests:
      #     memory: 33Gi
      #     storage: 120Gi
      # - namespace: virtual-machines
      #   limits:
      #     cpu: 40
      #   requests:
      #     memory: 150Gi
      #     storage: 1024Gi