{{- if eq .Values.csm.type "powerflex" }}
apiVersion: v1
{{- if .Values.csm.config.secret.encoded }}
data:
  config: {{ .Values.csm.config.secret.secretData }}
{{- else }}
stringData:
  config: {{- .Values.csm.config.secret.secretData | toYaml | indent 2 }}
{{- end }}
kind: Secret
metadata:
  name: {{ .Values.csm.config.secret.name }}
  namespace: {{ .Values.csm.namespace }}
{{- end }}