apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kotsadm.labels" . | nindent 4 }}
  name: kotsadm-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
