{{- if .Values.kotsadm.automation.license.slug }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kots.io/airgap: "false"
  labels:
    kots.io/app: {{ .Values.kotsadm.automation.license.slug }}
    kots.io/automation: license
    {{- include "kotsadm.labels" . | nindent 4 }}
  name: kotsadm-default-license
type: Opaque
data:
  license: {{ toYaml .Values.kotsadm.automation.license.data | b64enc }}
{{- end }}