apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "kotsadm.labels" . | nindent 4 }}
  name: kotsadm
spec:
  ports:
  - name: http
    port: 3000
    {{- if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    targetPort: http
  selector:
    app: kotsadm
  type: {{ .Values.service.type | quote }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
  {{- end}}