apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "kotsadm.labels" . | nindent 4 }}
  name: kotsadm-confg
data:
  app-version-label: ""
  ensure-rbac: "true"
  initial-app-images-pushed: "false"
  minio-enabled-snapshots: "true"
  registry-is-read-only: "false"
  skip-compatibility-check: "false"
  skip-rbac-check: "false"
  strict-security-context: "false"
  use-minimal-rbac: "false"
  wait-duration: 2m0s
  with-minio: "true"
  skip-preflights: {{ .Values.kotsadm.automation.skipPreflights | quote }}

