apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "kotsadm.labels" . | nindent 4 }}
  name: kotsadm-minio
spec:
  ports:
  - name: service
    port: 9000
    targetPort: 9000
  selector:
    app: kotsadm-minio
  type: ClusterIP
status:
  loadBalancer: {}
