apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "kotsadm.labels" . | nindent 4 }}
  name: kotsadm-postgres
data:
  passwd: |-
    root:x:0:0:root:/root:/bin/ash
    postgres:x:999:999:Linux User,,,:/var/lib/postgresql:/bin/sh

