{{- $jwtKey := uuidv4 | b64enc | quote }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "kotsadm-session") }}
{{- if $secret }}
{{- $jwtKey = index $secret.data "key" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "kotsadm.labels" . | nindent 4 }}
  name: kotsadm-session
  annotations:
    "helm.sh/resource-policy": "keep"
data:
  key: {{ $jwtKey }}