{{ if and .Values.scheduler.enabled (eq (lower .Values.scheduler.type) "deployment") }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "topolvm.fullname" . }}-scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "topolvm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.scheduler.service.type }}
  {{- with .Values.scheduler.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  selector:
    app.kubernetes.io/component: scheduler
    {{ include "topolvm.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.scheduler.options.listen.port }}
      {{- with .Values.scheduler.service.nodePort}}
      nodePort: {{ . }}
      {{- end }}
---
{{ end }}
