apiVersion: "amko.vmware.com/v1alpha1"
kind: "GSLBConfig"
metadata:
  name: "gc-1"
  namespace: {{ .Release.Namespace }}
  {{ if .Values.configs.amkoUUID }}
  {{ $length := len .Values.configs.amkoUUID }}
  {{ if ne $length 36 }}
  {{ fail "AMKO-UUID length should be equal to 36." }}
  {{ end }}
  annotations:
    amko.vmware.com/amko-uuid: {{ .Values.configs.amkoUUID }}
  {{ end }}
spec:
  gslbLeader:
    credentials: "gslb-avi-secret"
    controllerVersion: {{ .Values.configs.controllerVersion }}
    controllerIP: {{ .Values.configs.gslbLeaderController }}
    tenant: {{ .Values.configs.tenant }}
{{- with .Values.configs.memberClusters }}
  memberClusters:
    {{- toYaml . | nindent 4 }}
{{- end }}
  refreshInterval: {{ .Values.configs.refreshInterval }}
  logLevel: {{ .Values.configs.logLevel }}
  useCustomGlobalFqdn: {{ .Values.configs.useCustomGlobalFqdn}}