{{- if eq .Values.csm.type "powerflex" }}
apiVersion: v1
{{- if .Values.csm.config.secret.encrypted }}
data:
  config: {{ .Values.csm.config.secret.value }}
{{- else }}
stringData:
  config: {{- .Values.csm.config.secret.value | toYaml | indent 2 }}
{{- end }}
kind: Secret
metadata:
  name: {{ .Values.csm.config.secret.name }}
  namespace: {{ .Values.csm.namespace }}
{{- end }}