quotas:
  - namespace: default
    limits:
      cpu: 9
    requests:
      memory: 33Gi
      storage: 120Gi
  - namespace: virtual-machines
    limits:
      cpu: 40
    requests:
      memory: 150Gi
      storage: 1024Gi

rbac:
  - namespace: default
    viewers:
      groups:
        - Viewers Group 1
        - Viewers Group 2
  - namespace: virtual-machines
    admins:
      users:
        - test.user1@company.com
        - test.user2@company.com
      groups:
        - Test Group 1
        - Test Group 2
    powerusers:
      users: []
      groups: []
    users:
      users: []
      groups: []
    viewers:
      users: []
      groups: []
