{{- $nsname := .Release.Namespace -}}
{{- range $key, $value := .Values.configuration.bgppeers }}
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: {{ $key }}
  namespace: {{ $nsname }}
spec:
{{ .spec | toYaml | indent 2 }}
---
{{- end }}