{{- $nsname := .Release.Namespace -}}
{{- range $key, $value := .Values.configuration.communities }}
apiVersion: metallb.io/v1beta1
kind: Community
metadata:
  name: {{ $key }}
  namespace: {{ $nsname }}
spec:
{{ .spec | toYaml | indent 2 }}
---
{{- end }}