{{- $nsname := .Release.Namespace -}}
{{- range $key, $value := .Values.configuration.l2advertisements }}
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ $key }}
  namespace: {{ $nsname }}
spec:
{{ .spec | toYaml | indent 2 }}
---
{{- end }}