# This workflow will lint helm charts in packs and then push the packs to the configured Pack Repository

name: Lint helm charts and push packs to repo

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  PACK_REGISTRY: "packs-spectro.dreamworx.nl"

jobs:
  lint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Helm tool installer
      uses: Azure/setup-helm@v3

    - name: Checkout repo
      uses: actions/checkout@v3
    
    - name: Lint all Helm charts found in repo
      run: |
        shopt -s globstar
        ( for d in **/charts/*/; do helm lint $d --with-subcharts; if [ $? == 1 ]; then exit 1; fi; done )

  push:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Install Spectro CLI
      run: |
        wget -q https://spectro-cli.s3.amazonaws.com/v2.6.0/linux/spectro
        chmod +x spectro
        sudo mv spectro /usr/local/bin/
        spectro version

    - name: Login to Spectro Pack Registry
      env:
        PACK_USER: ${{ secrets.PACK_USER }}
        PACK_PASSWORD: ${{ secrets.PACK_PASSWORD }}
      run: |
        echo "$PACK_PASSWORD" | spectro registry login $PACK_REGISTRY --username $PACK_USER --password-stdin

    - name: Checkout repo
      uses: actions/checkout@v3
     
    - name: Push packs to Spectro Pack Registry
      env:
        PACK_USER: ${{ secrets.PACK_USER }}
        PACK_PASSWORD: ${{ secrets.PACK_PASSWORD }}
      run: |
        find stable -maxdepth 1 -mindepth 1 -exec spectro pack push -r $PACK_REGISTRY -f -m "Force pushed by Github Action" {} +
