# This workflow will lint helm charts in packs and then push the packs to the configured Pack Repository

name: Lint helm charts and push packs to repo

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  PACK_REGISTRY: "packs-spectro.dreamworx.nl"

jobs:
  lint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    # Installs Helm binary
    - name: Helm tool installer
      uses: Azure/setup-helm@v3

    # Checks out the repository this file is in
    - uses: actions/checkout@v3
    
    # Builds and pushes an image up to your Azure Container Registry
    - name: Lint all Helm charts found in repo
      run: |
        shopt -s globstar
        ( for d in **/charts/*/; do helm lint $d --with-subcharts; if [ $? == 1 ]; then exit 1; fi; done )

  push:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Install Spectro CLI
      run: |
        wget https://spectro-cli.s3.amazonaws.com/v2.6.0/linux/spectro
        chmod +x spectro
        spectro version

    - name: Login to Spectro Pack Registry
      env:
        PACK_USER: ${{ secrets.PACK_USER }}
        PACK_PASSWORD: ${{ secrets.PACK_PASSWORD }}
      run: |
        spectro registry login $PACK_REGISTRY --username $PACK_USER --password "$PACK_PASSWORD"

    # Checks out the repository this file is in
    #- uses: actions/checkout@v3
    # 
    #- name: Push packs to Spectro Pack Registry
    #  env:
    #    PACK_USER: ${{ secrets.PACK_USER }}
    #    PACK_PASSWORD: ${{ secrets.PACK_PASSWORD }}
    #  run: |
    #    spectro spectro pack push portworx-generic -r $PACK_REGISTRY
